---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: drain-node-on-crash
  labels:
    app: drain-node-on-crash
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: drain-node-on-crash
  namespace: kube-system

subjects:
  - name: drain-node-on-crash
    namespace: "kube-system"
    kind: ServiceAccount
