---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: drain-node-on-crash
  namespace: "kube-system"
  labels:
    app: drain-node-on-crash
rules:
  - apiGroups:
    - ""
    resources:
    - pods/eviction
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
  - apiGroups:
    - ""
    resources: 
    - endpoints
    verbs:
    - get
    - list
    - watch
    - update
    - create
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - list
    - watch
    - update
    - create
    - patch
    - delete
  - apiGroups:
    - apps
    resources:
    - statefulsets
    verbs:
    - get
    - list
  - apiGroups:
    - extensions
    - apps
    - ""
    resources:
    - daemonsets
    - replicasets
    verbs:
    - get
    - list
    - watch
    - update
    - create
    - patch
    - delete

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: drain-node-on-crash
  labels:
    app: drain-node-on-crash
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drain-node-on-crash
subjects:
  - name: drain-node-on-crash
    namespace: "kube-system"
    kind: ServiceAccount

